power: Fix compilation issue due to PDK upgrade
Added "stdlib.h" for fixing compilation error
(error: call to undeclared library function 'strtol')
due to PDK upgrade.

Change-Id: I520aa6589c6b6b72321afaebea49ba539e4a4931